
select * from json \G
/*create table history1 (
	temp_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	primary key (temp_id),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4*/